# Project information
site_author: Duodu Randy
site_name: MkDocs PDF Generate Plugin 
site_url: https://isolveit.github.io/mkdocs-pdf-generate/
copyright: Copyright &copy; 2023 4D Systems

# Repository information
repo_name: iSOLveIT/mkdocs-pdf-generate
repo_url: https://github.com/iSOLveIT/mkdocs-pdf-generate
edit_uri: edit/main/docs/docs/

theme:
  name: material
  logo: img/plugin_icon.svg
  favicon: img/plugin_favicon.png
  font:
    text: Barlow
    code: Fira Mono
  features:
      - search.suggest
      - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'white'
      accent: 'green'
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'white'
      accent: 'yellow'
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      
use_directory_urls: true

plugins:
  - search
  - minify:
      minify_html: true
  - pdf-generate:
#      debug: true
#      debug_target: changelog.md
      enable_csv: true
      copyright: Copyright &copy; 2023 4D Systems
      disclaimer: "Disclaimer: Content can change at anytime and best to refer to website for latest information."
#      include_legal_terms: true
      custom_template_path: cover_template
      toc_numbering: true
      toc_level: 6
      cover_images:
        default: img/cover.png
      enabled_if_env: ENABLE_PDF_EXPORT

nav:
  - Intro: index.md
  - Options: options.md
  - Customizations: customise/customisation.md
  - Changelog: changelog.md

markdown_extensions:
  - meta
  - toc:
      title: Table of Contents
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - def_list
